Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd, cwd + "/../include"]

group = DefineGroup('Lua', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
