require('and-or')
import arithmetics
require('typeof')
require('arithmetics-bignums')
require('bitwise-logic')
require('do-while')
require('equality')
require('for')
require('if-else')
require('logical')
require('octal')
require('switch-case')
require('try-catch-finally')
require('variables')
require('windows-line-ending')
require('new')
require('prototype')
require('regexp')
require('math')
require('math-abs')
require('math-exp')
require('math-log')
require('object')
require('array')
require('assignments')
require('function.prototype')
require('function-args')
# require('eval')
require('function-return')
require('object-create')
require('gc')
require('function_loop')
require('loop_arithmetics_10kk')
require('fill-array-with-numbers-3-times-5000-elements')
require('test_richards')
# require('array-prototype-indexof')
# require('object-keys')
# require('navier-stokes')
require('object-keys')

# require('test_deltablue')

require('object-assgin')

# require('object-defineproperty')

#require('object-get-own-property-names')

# require('string')
