Import('RTT_ROOT')
Import('rtconfig')
Import('logger')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd, str(Dir('#'))]

logger.info(src)
for s in src:
    logger.info(type(s))
    logger.info(s.get_abspath())
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
