HEADERS += \
    $$PWD/lv_examples/lv_apps/benchmark/benchmark.h \
    $$PWD/lv_examples/lv_apps/demo/demo.h \
    $$PWD/lv_examples/lv_apps/sysmon/sysmon.h \
    $$PWD/lv_examples/lv_apps/terminal/terminal.h \
    $$PWD/lv_examples/lv_apps/tpcal/tpcal.h \
    $$PWD/lv_examples/lv_tests/lv_test_group/lv_test_group.h \
    $$PWD/lv_examples/lv_tests/lv_test_misc/lv_test_task.h \
    $$PWD/lv_examples/lv_tests/lv_test_obj/lv_test_obj.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_arc/lv_test_arc.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_bar/lv_test_bar.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_btn/lv_test_btn.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_btnm/lv_test_btnm.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_canvas/lv_test_canvas.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_cb/lv_test_cb.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_chart/lv_test_chart.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_cont/lv_test_cont.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_cpicker/lv_test_cpicker.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_ddlist/lv_test_ddlist.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_gauge/lv_test_gauge.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_img/lv_test_img.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/lv_test_imgbtn.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_kb/lv_test_kb.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_label/lv_test_label.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_led/lv_test_led.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_line/lv_test_line.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_list/lv_test_list.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_lmeter/lv_test_lmeter.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_mbox/lv_test_mbox.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_page/lv_test_page.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_preload/lv_test_preload.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_roller/lv_test_roller.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_slider/lv_test_slider.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_sw/lv_test_sw.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_ta/lv_test_ta.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_table/lv_test_table.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_tabview/lv_test_tabview.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_tileview/lv_test_tileview.h \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_win/lv_test_win.h \
    $$PWD/lv_examples/lv_tests/lv_test_stress/lv_test_stress.h \
    $$PWD/lv_examples/lv_tests/lv_test_theme/lv_test_theme_1.h \
    $$PWD/lv_examples/lv_tests/lv_test_theme/lv_test_theme_2.h \
    $$PWD/lv_examples/lv_tests/lv_test.h \
    $$PWD/lv_examples/lv_tutorial/10_keyboard/lv_tutorial_keyboard.h \
    $$PWD/lv_examples/lv_tutorial/1_hello_world/lv_tutorial_hello_world.h \
    $$PWD/lv_examples/lv_tutorial/2_objects/lv_tutorial_objects.h \
    $$PWD/lv_examples/lv_tutorial/3_styles/lv_tutorial_styles.h \
    $$PWD/lv_examples/lv_tutorial/4_themes/lv_tutorial_themes.h \
    $$PWD/lv_examples/lv_tutorial/5_antialiasing/lv_tutorial_antialiasing.h \
    $$PWD/lv_examples/lv_tutorial/6_images/lv_tutorial_images.h \
    $$PWD/lv_examples/lv_tutorial/7_fonts/lv_tutorial_fonts.h \
    $$PWD/lv_examples/lv_tutorial/8_animations/lv_tutorial_animations.h \
    $$PWD/lv_examples/lv_tutorial/9_responsive/lv_tutorial_responsive.h \
    $$PWD/lv_examples/lv_ex_conf_templ.h \
    $$PWD/lv_examples/lv_examples.h

SOURCES += \
    $$PWD/lv_examples/lv_apps/benchmark/benchmark.c \
    $$PWD/lv_examples/lv_apps/benchmark/benchmark_bg.c \
    $$PWD/lv_examples/lv_apps/demo/demo.c \
    $$PWD/lv_examples/lv_apps/demo/img_bubble_pattern.c \
    $$PWD/lv_examples/lv_apps/sysmon/sysmon.c \
    $$PWD/lv_examples/lv_apps/terminal/terminal.c \
    $$PWD/lv_examples/lv_apps/tpcal/tpcal.c \
    $$PWD/lv_examples/lv_tests/lv_test_group/lv_test_group.c \
    $$PWD/lv_examples/lv_tests/lv_test_misc/lv_test_task.c \
    $$PWD/lv_examples/lv_tests/lv_test_obj/lv_test_obj.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_arc/lv_test_arc.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_bar/lv_test_bar.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_btn/lv_test_btn.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_btnm/lv_test_btnm.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_canvas/lv_test_canvas.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_cb/lv_test_cb.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_chart/lv_test_chart.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_cont/lv_test_cont.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_cpicker/lv_test_cpicker.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_ddlist/lv_test_ddlist.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_gauge/lv_test_gauge.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_img/img_flower_icon.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_img/lv_test_img.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_1.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_2.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_3.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_4.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/lv_test_imgbtn.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_kb/lv_test_kb.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_label/lv_test_label.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_led/lv_test_led.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_line/lv_test_line.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_list/lv_test_list.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_lmeter/lv_test_lmeter.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_mbox/lv_test_mbox.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_page/lv_test_page.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_preload/lv_test_preload.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_roller/lv_test_roller.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_slider/lv_test_slider.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_sw/lv_test_sw.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_ta/lv_test_ta.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_table/lv_test_table.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_tabview/lv_test_tabview.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_tileview/lv_test_tileview.c \
    $$PWD/lv_examples/lv_tests/lv_test_objx/lv_test_win/lv_test_win.c \
    $$PWD/lv_examples/lv_tests/lv_test_stress/lv_test_stress.c \
    $$PWD/lv_examples/lv_tests/lv_test_theme/lv_test_theme_1.c \
    $$PWD/lv_examples/lv_tests/lv_test_theme/lv_test_theme_2.c \
    $$PWD/lv_examples/lv_tutorial/10_keyboard/lv_tutorial_keyboard.c \
    $$PWD/lv_examples/lv_tutorial/1_hello_world/lv_tutorial_hello_world.c \
    $$PWD/lv_examples/lv_tutorial/2_objects/lv_tutorial_objects.c \
    $$PWD/lv_examples/lv_tutorial/3_styles/lv_tutorial_styles.c \
    $$PWD/lv_examples/lv_tutorial/4_themes/lv_tutorial_themes.c \
    $$PWD/lv_examples/lv_tutorial/5_antialiasing/apple_icon_alpha.c \
    $$PWD/lv_examples/lv_tutorial/5_antialiasing/apple_icon_chroma.c \
    $$PWD/lv_examples/lv_tutorial/5_antialiasing/lv_tutorial_antialiasing.c \
    $$PWD/lv_examples/lv_tutorial/6_images/flower_icon_alpha.c \
    $$PWD/lv_examples/lv_tutorial/6_images/lv_tutorial_images.c \
    $$PWD/lv_examples/lv_tutorial/6_images/red_flower.c \
    $$PWD/lv_examples/lv_tutorial/6_images/red_rose_16.c \
    $$PWD/lv_examples/lv_tutorial/7_fonts/arial_20.c \
    $$PWD/lv_examples/lv_tutorial/7_fonts/lv_tutorial_fonts.c \
    $$PWD/lv_examples/lv_tutorial/8_animations/lv_tutorial_animations.c \
    $$PWD/lv_examples/lv_tutorial/9_responsive/lv_tutorial_responsive.c
